FROM php:8.4-fpm

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libpq-dev \
    libicu-dev \
    mariadb-client \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        pdo_mysql \
        pdo_pgsql \
        intl \
        zip \
        bcmath \
        pcntl \
    && pecl install redis \
    && docker-php-ext-enable redis

# Desactivar opcache en dev
RUN echo "opcache.enable=0" > /usr/local/etc/php/conf.d/opcache-dev.ini

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

ARG UID=1000
ARG GID=1000
RUN groupadd -g $GID dev && useradd -u $UID -g dev -m dev
USER dev

CMD ["php-fpm"]
